/* soapBasicHttpBinding_USCOREIServiceProxy.h
   Generated by gSOAP 2.8.22 from wssoap.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapBasicHttpBinding_USCOREIServiceProxy_H
#define soapBasicHttpBinding_USCOREIServiceProxy_H
#include "soapH.h"

class SOAP_CMAC BasicHttpBinding_USCOREIServiceProxy
{ public:
	struct soap *soap;
	bool soap_own;
	/// Endpoint URL of service 'BasicHttpBinding_USCOREIServiceProxy' (change as needed)
	const char *soap_endpoint;
	/// Variables globally declared in wssoap.h (non-static)
	/// Constructor
	BasicHttpBinding_USCOREIServiceProxy();
	/// Constructor to use/share an engine state
	BasicHttpBinding_USCOREIServiceProxy(struct soap*);
	/// Constructor with endpoint URL
	BasicHttpBinding_USCOREIServiceProxy(const char *url);
	/// Constructor with engine input+output mode control
	BasicHttpBinding_USCOREIServiceProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	BasicHttpBinding_USCOREIServiceProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	BasicHttpBinding_USCOREIServiceProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~BasicHttpBinding_USCOREIServiceProxy();
	/// Initializer used by constructors
	virtual	void BasicHttpBinding_USCOREIServiceProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'GetLink' (returns error code or SOAP_OK)
	virtual	int GetLink(_tempuri__GetLink *tempuri__GetLink, _tempuri__GetLinkResponse &tempuri__GetLinkResponse) { return this->GetLink(NULL, NULL, tempuri__GetLink, tempuri__GetLinkResponse); }
	virtual	int GetLink(const char *endpoint, const char *soap_action, _tempuri__GetLink *tempuri__GetLink, _tempuri__GetLinkResponse &tempuri__GetLinkResponse);

	/// Web service operation 'GetNamesDictionary' (returns error code or SOAP_OK)
	virtual	int GetNamesDictionary(_tempuri__GetNamesDictionary *tempuri__GetNamesDictionary, _tempuri__GetNamesDictionaryResponse &tempuri__GetNamesDictionaryResponse) { return this->GetNamesDictionary(NULL, NULL, tempuri__GetNamesDictionary, tempuri__GetNamesDictionaryResponse); }
	virtual	int GetNamesDictionary(const char *endpoint, const char *soap_action, _tempuri__GetNamesDictionary *tempuri__GetNamesDictionary, _tempuri__GetNamesDictionaryResponse &tempuri__GetNamesDictionaryResponse);

	/// Web service operation 'SendLinks' (returns error code or SOAP_OK)
	virtual	int SendLinks(_tempuri__SendLinks *tempuri__SendLinks, _tempuri__SendLinksResponse &tempuri__SendLinksResponse) { return this->SendLinks(NULL, NULL, tempuri__SendLinks, tempuri__SendLinksResponse); }
	virtual	int SendLinks(const char *endpoint, const char *soap_action, _tempuri__SendLinks *tempuri__SendLinks, _tempuri__SendLinksResponse &tempuri__SendLinksResponse);

	/// Web service operation 'SendAmountDictionary' (returns error code or SOAP_OK)
	virtual	int SendAmountDictionary(_tempuri__SendAmountDictionary *tempuri__SendAmountDictionary, _tempuri__SendAmountDictionaryResponse &tempuri__SendAmountDictionaryResponse) { return this->SendAmountDictionary(NULL, NULL, tempuri__SendAmountDictionary, tempuri__SendAmountDictionaryResponse); }
	virtual	int SendAmountDictionary(const char *endpoint, const char *soap_action, _tempuri__SendAmountDictionary *tempuri__SendAmountDictionary, _tempuri__SendAmountDictionaryResponse &tempuri__SendAmountDictionaryResponse);

	/// Web service operation 'GetStats' (returns error code or SOAP_OK)
	virtual	int GetStats(_tempuri__GetStats *tempuri__GetStats, _tempuri__GetStatsResponse &tempuri__GetStatsResponse) { return this->GetStats(NULL, NULL, tempuri__GetStats, tempuri__GetStatsResponse); }
	virtual	int GetStats(const char *endpoint, const char *soap_action, _tempuri__GetStats *tempuri__GetStats, _tempuri__GetStatsResponse &tempuri__GetStatsResponse);

	/// Web service operation 'GetDailyStats' (returns error code or SOAP_OK)
	virtual	int GetDailyStats(_tempuri__GetDailyStats *tempuri__GetDailyStats, _tempuri__GetDailyStatsResponse &tempuri__GetDailyStatsResponse) { return this->GetDailyStats(NULL, NULL, tempuri__GetDailyStats, tempuri__GetDailyStatsResponse); }
	virtual	int GetDailyStats(const char *endpoint, const char *soap_action, _tempuri__GetDailyStats *tempuri__GetDailyStats, _tempuri__GetDailyStatsResponse &tempuri__GetDailyStatsResponse);

	/// Web service operation 'GetStatsByName' (returns error code or SOAP_OK)
	virtual	int GetStatsByName(_tempuri__GetStatsByName *tempuri__GetStatsByName, _tempuri__GetStatsByNameResponse &tempuri__GetStatsByNameResponse) { return this->GetStatsByName(NULL, NULL, tempuri__GetStatsByName, tempuri__GetStatsByNameResponse); }
	virtual	int GetStatsByName(const char *endpoint, const char *soap_action, _tempuri__GetStatsByName *tempuri__GetStatsByName, _tempuri__GetStatsByNameResponse &tempuri__GetStatsByNameResponse);

	/// Web service operation 'GetNames' (returns error code or SOAP_OK)
	virtual	int GetNames(_tempuri__GetNames *tempuri__GetNames, _tempuri__GetNamesResponse &tempuri__GetNamesResponse) { return this->GetNames(NULL, NULL, tempuri__GetNames, tempuri__GetNamesResponse); }
	virtual	int GetNames(const char *endpoint, const char *soap_action, _tempuri__GetNames *tempuri__GetNames, _tempuri__GetNamesResponse &tempuri__GetNamesResponse);

	/// Web service operation 'GetSites' (returns error code or SOAP_OK)
	virtual	int GetSites(_tempuri__GetSites *tempuri__GetSites, _tempuri__GetSitesResponse &tempuri__GetSitesResponse) { return this->GetSites(NULL, NULL, tempuri__GetSites, tempuri__GetSitesResponse); }
	virtual	int GetSites(const char *endpoint, const char *soap_action, _tempuri__GetSites *tempuri__GetSites, _tempuri__GetSitesResponse &tempuri__GetSitesResponse);

	/// Web service operation 'GetPages' (returns error code or SOAP_OK)
	virtual	int GetPages(_tempuri__GetPages *tempuri__GetPages, _tempuri__GetPagesResponse &tempuri__GetPagesResponse) { return this->GetPages(NULL, NULL, tempuri__GetPages, tempuri__GetPagesResponse); }
	virtual	int GetPages(const char *endpoint, const char *soap_action, _tempuri__GetPages *tempuri__GetPages, _tempuri__GetPagesResponse &tempuri__GetPagesResponse);

	/// Web service operation 'GetSearchPhrases' (returns error code or SOAP_OK)
	virtual	int GetSearchPhrases(_tempuri__GetSearchPhrases *tempuri__GetSearchPhrases, _tempuri__GetSearchPhrasesResponse &tempuri__GetSearchPhrasesResponse) { return this->GetSearchPhrases(NULL, NULL, tempuri__GetSearchPhrases, tempuri__GetSearchPhrasesResponse); }
	virtual	int GetSearchPhrases(const char *endpoint, const char *soap_action, _tempuri__GetSearchPhrases *tempuri__GetSearchPhrases, _tempuri__GetSearchPhrasesResponse &tempuri__GetSearchPhrasesResponse);

	/// Web service operation 'SetSite' (returns error code or SOAP_OK)
	virtual	int SetSite(_tempuri__SetSite *tempuri__SetSite, _tempuri__SetSiteResponse &tempuri__SetSiteResponse) { return this->SetSite(NULL, NULL, tempuri__SetSite, tempuri__SetSiteResponse); }
	virtual	int SetSite(const char *endpoint, const char *soap_action, _tempuri__SetSite *tempuri__SetSite, _tempuri__SetSiteResponse &tempuri__SetSiteResponse);

	/// Web service operation 'SetName' (returns error code or SOAP_OK)
	virtual	int SetName(_tempuri__SetName *tempuri__SetName, _tempuri__SetNameResponse &tempuri__SetNameResponse) { return this->SetName(NULL, NULL, tempuri__SetName, tempuri__SetNameResponse); }
	virtual	int SetName(const char *endpoint, const char *soap_action, _tempuri__SetName *tempuri__SetName, _tempuri__SetNameResponse &tempuri__SetNameResponse);

	/// Web service operation 'SetSearchPhrase' (returns error code or SOAP_OK)
	virtual	int SetSearchPhrase(_tempuri__SetSearchPhrase *tempuri__SetSearchPhrase, _tempuri__SetSearchPhraseResponse &tempuri__SetSearchPhraseResponse) { return this->SetSearchPhrase(NULL, NULL, tempuri__SetSearchPhrase, tempuri__SetSearchPhraseResponse); }
	virtual	int SetSearchPhrase(const char *endpoint, const char *soap_action, _tempuri__SetSearchPhrase *tempuri__SetSearchPhrase, _tempuri__SetSearchPhraseResponse &tempuri__SetSearchPhraseResponse);
};
#endif
