/* soapBasicHttpBinding_USCOREIServiceProxy.h
   Generated by gSOAP 2.8.22 from wssoap.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapBasicHttpBinding_USCOREIServiceProxy_H
#define soapBasicHttpBinding_USCOREIServiceProxy_H
#include "soapH.h"

class SOAP_CMAC BasicHttpBinding_USCOREIServiceProxy
{ public:
	struct soap *soap;
	bool soap_own;
	/// Endpoint URL of service 'BasicHttpBinding_USCOREIServiceProxy' (change as needed)
	const char *soap_endpoint;
	/// Variables globally declared in wssoap.h (non-static)
	/// Constructor
	BasicHttpBinding_USCOREIServiceProxy();
	/// Constructor to use/share an engine state
	BasicHttpBinding_USCOREIServiceProxy(struct soap*);
	/// Constructor with endpoint URL
	BasicHttpBinding_USCOREIServiceProxy(const char *url);
	/// Constructor with engine input+output mode control
	BasicHttpBinding_USCOREIServiceProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	BasicHttpBinding_USCOREIServiceProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	BasicHttpBinding_USCOREIServiceProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~BasicHttpBinding_USCOREIServiceProxy();
	/// Initializer used by constructors
	virtual	void BasicHttpBinding_USCOREIServiceProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'GetLink' (returns error code or SOAP_OK)
	virtual	int GetLink(_ns1__GetLink *ns1__GetLink, _ns1__GetLinkResponse &ns1__GetLinkResponse) { return this->GetLink(NULL, NULL, ns1__GetLink, ns1__GetLinkResponse); }
	virtual	int GetLink(const char *endpoint, const char *soap_action, _ns1__GetLink *ns1__GetLink, _ns1__GetLinkResponse &ns1__GetLinkResponse);

	/// Web service operation 'GetNamesDictionary' (returns error code or SOAP_OK)
	virtual	int GetNamesDictionary(_ns1__GetNamesDictionary *ns1__GetNamesDictionary, _ns1__GetNamesDictionaryResponse &ns1__GetNamesDictionaryResponse) { return this->GetNamesDictionary(NULL, NULL, ns1__GetNamesDictionary, ns1__GetNamesDictionaryResponse); }
	virtual	int GetNamesDictionary(const char *endpoint, const char *soap_action, _ns1__GetNamesDictionary *ns1__GetNamesDictionary, _ns1__GetNamesDictionaryResponse &ns1__GetNamesDictionaryResponse);

	/// Web service operation 'SendLinks' (returns error code or SOAP_OK)
	virtual	int SendLinks(_ns1__SendLinks *ns1__SendLinks, _ns1__SendLinksResponse &ns1__SendLinksResponse) { return this->SendLinks(NULL, NULL, ns1__SendLinks, ns1__SendLinksResponse); }
	virtual	int SendLinks(const char *endpoint, const char *soap_action, _ns1__SendLinks *ns1__SendLinks, _ns1__SendLinksResponse &ns1__SendLinksResponse);

	/// Web service operation 'SendAmountDictionary' (returns error code or SOAP_OK)
	virtual	int SendAmountDictionary(_ns1__SendAmountDictionary *ns1__SendAmountDictionary, _ns1__SendAmountDictionaryResponse &ns1__SendAmountDictionaryResponse) { return this->SendAmountDictionary(NULL, NULL, ns1__SendAmountDictionary, ns1__SendAmountDictionaryResponse); }
	virtual	int SendAmountDictionary(const char *endpoint, const char *soap_action, _ns1__SendAmountDictionary *ns1__SendAmountDictionary, _ns1__SendAmountDictionaryResponse &ns1__SendAmountDictionaryResponse);

	/// Web service operation 'GetStats' (returns error code or SOAP_OK)
	virtual	int GetStats(_ns1__GetStats *ns1__GetStats, _ns1__GetStatsResponse &ns1__GetStatsResponse) { return this->GetStats(NULL, NULL, ns1__GetStats, ns1__GetStatsResponse); }
	virtual	int GetStats(const char *endpoint, const char *soap_action, _ns1__GetStats *ns1__GetStats, _ns1__GetStatsResponse &ns1__GetStatsResponse);

	/// Web service operation 'GetDailyStats' (returns error code or SOAP_OK)
	virtual	int GetDailyStats(_ns1__GetDailyStats *ns1__GetDailyStats, _ns1__GetDailyStatsResponse &ns1__GetDailyStatsResponse) { return this->GetDailyStats(NULL, NULL, ns1__GetDailyStats, ns1__GetDailyStatsResponse); }
	virtual	int GetDailyStats(const char *endpoint, const char *soap_action, _ns1__GetDailyStats *ns1__GetDailyStats, _ns1__GetDailyStatsResponse &ns1__GetDailyStatsResponse);

	/// Web service operation 'GetStatsByName' (returns error code or SOAP_OK)
	virtual	int GetStatsByName(_ns1__GetStatsByName *ns1__GetStatsByName, _ns1__GetStatsByNameResponse &ns1__GetStatsByNameResponse) { return this->GetStatsByName(NULL, NULL, ns1__GetStatsByName, ns1__GetStatsByNameResponse); }
	virtual	int GetStatsByName(const char *endpoint, const char *soap_action, _ns1__GetStatsByName *ns1__GetStatsByName, _ns1__GetStatsByNameResponse &ns1__GetStatsByNameResponse);

	/// Web service operation 'GetNames' (returns error code or SOAP_OK)
	virtual	int GetNames(_ns1__GetNames *ns1__GetNames, _ns1__GetNamesResponse &ns1__GetNamesResponse) { return this->GetNames(NULL, NULL, ns1__GetNames, ns1__GetNamesResponse); }
	virtual	int GetNames(const char *endpoint, const char *soap_action, _ns1__GetNames *ns1__GetNames, _ns1__GetNamesResponse &ns1__GetNamesResponse);

	/// Web service operation 'GetSites' (returns error code or SOAP_OK)
	virtual	int GetSites(_ns1__GetSites *ns1__GetSites, _ns1__GetSitesResponse &ns1__GetSitesResponse) { return this->GetSites(NULL, NULL, ns1__GetSites, ns1__GetSitesResponse); }
	virtual	int GetSites(const char *endpoint, const char *soap_action, _ns1__GetSites *ns1__GetSites, _ns1__GetSitesResponse &ns1__GetSitesResponse);

	/// Web service operation 'GetPages' (returns error code or SOAP_OK)
	virtual	int GetPages(_ns1__GetPages *ns1__GetPages, _ns1__GetPagesResponse &ns1__GetPagesResponse) { return this->GetPages(NULL, NULL, ns1__GetPages, ns1__GetPagesResponse); }
	virtual	int GetPages(const char *endpoint, const char *soap_action, _ns1__GetPages *ns1__GetPages, _ns1__GetPagesResponse &ns1__GetPagesResponse);

	/// Web service operation 'GetSearchPhrases' (returns error code or SOAP_OK)
	virtual	int GetSearchPhrases(_ns1__GetSearchPhrases *ns1__GetSearchPhrases, _ns1__GetSearchPhrasesResponse &ns1__GetSearchPhrasesResponse) { return this->GetSearchPhrases(NULL, NULL, ns1__GetSearchPhrases, ns1__GetSearchPhrasesResponse); }
	virtual	int GetSearchPhrases(const char *endpoint, const char *soap_action, _ns1__GetSearchPhrases *ns1__GetSearchPhrases, _ns1__GetSearchPhrasesResponse &ns1__GetSearchPhrasesResponse);

	/// Web service operation 'SetSite' (returns error code or SOAP_OK)
	virtual	int SetSite(_ns1__SetSite *ns1__SetSite, _ns1__SetSiteResponse &ns1__SetSiteResponse) { return this->SetSite(NULL, NULL, ns1__SetSite, ns1__SetSiteResponse); }
	virtual	int SetSite(const char *endpoint, const char *soap_action, _ns1__SetSite *ns1__SetSite, _ns1__SetSiteResponse &ns1__SetSiteResponse);

	/// Web service operation 'SetName' (returns error code or SOAP_OK)
	virtual	int SetName(_ns1__SetName *ns1__SetName, _ns1__SetNameResponse &ns1__SetNameResponse) { return this->SetName(NULL, NULL, ns1__SetName, ns1__SetNameResponse); }
	virtual	int SetName(const char *endpoint, const char *soap_action, _ns1__SetName *ns1__SetName, _ns1__SetNameResponse &ns1__SetNameResponse);

	/// Web service operation 'SetSearchPhrase' (returns error code or SOAP_OK)
	virtual	int SetSearchPhrase(_ns1__SetSearchPhrase *ns1__SetSearchPhrase, _ns1__SetSearchPhraseResponse &ns1__SetSearchPhraseResponse) { return this->SetSearchPhrase(NULL, NULL, ns1__SetSearchPhrase, ns1__SetSearchPhraseResponse); }
	virtual	int SetSearchPhrase(const char *endpoint, const char *soap_action, _ns1__SetSearchPhrase *ns1__SetSearchPhrase, _ns1__SetSearchPhraseResponse &ns1__SetSearchPhraseResponse);
};
#endif
